services:
  db:
    image: postgres:latest
    container_name: postgres-shoppingcart
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shoppingcart
    ports:
      - "54321:5432"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: .
      args:
        SKIP_TESTS: "false"
    container_name: shoppingcart-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shoppingcart
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

volumes:
  db:
    driver: local